// Code generated by: https://github.com/OpenNSPW/Disassembler

using Aigamo.Enzan;

namespace OpenNspw.Interop.Subroutines
{
	// scenario_3
	internal static class Sub42AA60
	{
		public static void Call(Emulator emulator)
		{
			emulator.Cpu.Push(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Mov(emulator.Cpu.Esp);
			emulator.Cpu.Esp = emulator.Cpu.And(emulator.Cpu.Esp, new Register8(0xF8/*-8*/));
			emulator.Cpu.Esp = emulator.Cpu.Sub(emulator.Cpu.Esp, new Register8(0x14/*20*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register32(0x40668000/*1080459264*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0868000/*3230040064*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0AFE000/*3232751616*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x0B/*11*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Memory16[new Register32(0x00443A90/*4471440*/)] = emulator.Cpu.Mov(new Register16(0x0064/*100*/));
			emulator.Memory16[new Register32(0x00489FB0/*4759472*/)] = emulator.Cpu.Mov(new Register16(0x0002/*2*/));
			emulator.Memory16[new Register32(0x00483B4C/*4733772*/)] = emulator.Cpu.Mov(new Register16(0x0001/*1*/));
			emulator.Memory32[new Register32(0x00489AB0/*4758192*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489AB4/*4758196*/)] = emulator.Cpu.Mov(new Register32(0xC0B18000/*3232858112*/));
			emulator.Memory32[new Register32(0x00489AB8/*4758200*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489ABC/*4758204*/)] = emulator.Cpu.Mov(new Register32(0xC0740000/*3228827648*/));
			emulator.Memory32[new Register32(0x00443A48/*4471368*/)] = emulator.Cpu.Mov(new Register32(0x00004E20/*20000*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x10/*16*/));
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x08/*8*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x04/*4*/));
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x50/*80*/));
			emulator.Cpu.Push(new Register32(0x40668000/*1080459264*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC08B8000/*3230367744*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0AF4000/*3232710656*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x0F/*15*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Call(new Register32(0x00436056/*4415574*/));
			emulator.Cpu.Eax = emulator.Cpu.And(emulator.Cpu.Eax, new Register32(0x80000001/*2147483649*/));
			if (emulator.Cpu.Jns) goto loc_42AB2E;
			emulator.Cpu.Eax = emulator.Cpu.Dec(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Or(emulator.Cpu.Eax, new Register8(0xFE/*-2*/));
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);

			loc_42AB2E:
			if (emulator.Cpu.Je) goto loc_42AB62;
			emulator.Cpu.Call(new Register32(0x00436056/*4415574*/));
			emulator.Cpu.Cdq();
			emulator.Cpu.Ecx = emulator.Cpu.Mov(new Register32(0x00000FA0/*4000*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x40990000/*1083768832*/));
			emulator.Cpu.Idiv(emulator.Cpu.Ecx);
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0xFFFFF768/*4294965096*/));
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000018/*24*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			goto loc_42AB92;

			loc_42AB62:
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000018/*24*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(new Register32(0xC0A13000/*3231789056*/));
			emulator.Cpu.Call(new Register32(0x00436056/*4415574*/));
			emulator.Cpu.Cdq();
			emulator.Cpu.Ecx = emulator.Cpu.Mov(new Register32(0x00000FA0/*4000*/));
			emulator.Cpu.Idiv(emulator.Cpu.Ecx);
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000640/*1600*/));
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42AB92:
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000018/*24*/)]);
			emulator.Cpu.Push(new Register32(0x4060E000/*1080090624*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Push(emulator.Cpu.Ecx);
			emulator.Cpu.Push(emulator.Cpu.Edx);
			emulator.Cpu.Push(new Register8(0x05/*5*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x10/*16*/));
			emulator.Cpu.Push(new Register8(0x09/*9*/));
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x08/*8*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Memory16[new Register32(0x00486C3A/*4746298*/)] = emulator.Cpu.Mov(emulator.Cpu.Si);
			emulator.Memory16[new Register32(0x00487088/*4747400*/)] = emulator.Cpu.Mov(emulator.Cpu.Si);
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x03/*3*/));
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4062C00000000000)/*150*/);
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x50/*80*/));
			emulator.Cpu.Push(new Register32(0x4060E000/*1080090624*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000024/*36*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(emulator.Cpu.Ecx);
			emulator.Cpu.Push(new Register8(0x03/*3*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4062C00000000000)/*150*/);
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Memory16[new Register32(0x0048708A/*4747402*/)] = emulator.Cpu.Mov(emulator.Cpu.Ax);
			emulator.Cpu.Push(new Register32(0x4060E000/*1080090624*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Esp = emulator.Cpu.Sub(emulator.Cpu.Esp, new Register8(0x08/*8*/));
			emulator.Memory64[emulator.Cpu.Esp] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x0F/*15*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Memory16[new Register32(0x0048708C/*4747404*/)] = emulator.Cpu.Mov(emulator.Cpu.Ax);
			emulator.Memory16[new Register32(0x00486C3C/*4746300*/)] = emulator.Cpu.Mov(new Register16(0x0001/*1*/));
			emulator.Memory16[new Register32(0x00486C3E/*4746302*/)] = emulator.Cpu.Mov(new Register16(0x0001/*1*/));
			emulator.Cpu.Call(new Register32(0x0041F230/*4321840*/));
			emulator.Cpu.Push(new Register8(0x0B/*11*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x0041F230/*4321840*/));
			emulator.Cpu.Push(new Register8(0x01/*1*/));
			emulator.Cpu.Call(new Register32(0x00404D80/*4214144*/));
			emulator.Cpu.Push(new Register32(0x004415C8/*4462024*/));
			emulator.Cpu.Call(new Register32(0x00432A30/*4401712*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x38/*56*/));
			emulator.Cpu.Edi = emulator.Cpu.Pop32();
			emulator.Cpu.Esi = emulator.Cpu.Pop32();
			emulator.Cpu.Ebx = emulator.Cpu.Pop32();
			emulator.Cpu.Esp = emulator.Cpu.Mov(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Pop32();
			return;

		}
	}
}