// Code generated by: https://github.com/OpenNSPW/Disassembler

using Aigamo.Enzan;

namespace OpenNspw.Interop.Subroutines
{
	// set_cpu_route2
	internal static class Sub42ED30
	{
		public static void Call(Emulator emulator)
		{
			emulator.Cpu.Push(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Mov(emulator.Cpu.Esp);
			emulator.Cpu.Esp = emulator.Cpu.And(emulator.Cpu.Esp, new Register8(0xF8/*-8*/));
			emulator.Cpu.Esp = emulator.Cpu.Sub(emulator.Cpu.Esp, new Register32(0x0000012C/*300*/));
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463B20/*4602656*/)]);
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42ED59;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463AA4/*4602532*/)]);
			emulator.Cpu.Push(new Register32(0x0044166C/*4462188*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(emulator.Memory32[new Register32(0x0043C154/*4440404*/)]);

			loc_42ED59:
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000074/*116*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Cpu.Esi = emulator.Cpu.Lea(emulator.Cpu.Edi + emulator.Cpu.Edi * new Register32(4));
			emulator.Cpu.Esi = emulator.Cpu.Lea(emulator.Cpu.Esi + emulator.Cpu.Esi * new Register32(8));
			emulator.Cpu.Esi = emulator.Cpu.Shl(emulator.Cpu.Esi, new Register8(0x02/*2*/));
			emulator.Cpu.Esi = emulator.Cpu.Sub(emulator.Cpu.Esi, emulator.Cpu.Edi);
			emulator.Cpu.Esi = emulator.Cpu.Shl(emulator.Cpu.Esi, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000084/*132*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x004916B8/*4789944*/)], emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42EF7A;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)]);
			emulator.Cpu.Cmp(emulator.Memory16[new Register32(0x00443A90/*4471440*/)], emulator.Cpu.Ax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000024/*36*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jl) goto loc_42EEA0;
			emulator.Cpu.Ebx = emulator.Cpu.Mov(new Register32(0x00491C54/*4791380*/));

			loc_42EDC8:
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Ebx + new Register32(0x000000E4/*228*/)], new Register8(0x00/*0*/));
			if (emulator.Cpu.Je) goto loc_42EE7F;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42EE7F;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Ebx + new Register32(0x000000FC/*252*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42EE7F;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebx]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			if (emulator.Cpu.Jne) goto loc_42EDFE;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebx + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Test(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_42EE7F;

			loc_42EDFE:
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0C/*12*/));
			if (emulator.Cpu.Je) goto loc_42EE7F;
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0B/*11*/));
			if (emulator.Cpu.Je) goto loc_42EE7F;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ebx + new Register32(0x000000F4/*244*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ebx + new Register32(0x000000EC/*236*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Edi = emulator.Cpu.Sar(emulator.Cpu.Edi, new Register8(1));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000008C/*140*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Edi * new Register32(1));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Add(emulator.Cpu.Edx, emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000090/*144*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000094/*148*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000088/*136*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Esp + new Register32(0x00000090/*144*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x00417BE0/*4291552*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x0C/*12*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42FF5E;

			loc_42EE7F:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, new Register32(0x00000598/*1432*/));
			emulator.Cpu.Ecx = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_42EDC8;
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);

			loc_42EEA0:
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000024/*36*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42EF7A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0BC200000000000)/*-7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42EF7A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42EF7A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x40C2C00000000000)/*9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42EF7A;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Fld(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2E0/*4760288*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Shl(emulator.Cpu.Ebx, new Register8(0x08/*8*/));
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2DC/*4760284*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Ebx * new Register32(2) + new Register32(0x00443AA0/*4471456*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jae) goto loc_42FF5E;

			loc_42EF7A:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000058/*88*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000006C/*108*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Edi + emulator.Cpu.Edi * new Register32(4));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000054/*84*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000005C/*92*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(8));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Shl(emulator.Cpu.Eax, new Register8(0x02/*2*/));
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);

			loc_42EFC9:
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Test(emulator.Cpu.Edi, emulator.Cpu.Edi);
			if (emulator.Cpu.Jne) goto loc_42F00C;
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000084/*132*/)]);
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edx + new Register32(0x004916A8/*4789928*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edx + new Register32(0x004916AC/*4789932*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edx + new Register32(0x004916B0/*4789936*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000009C/*156*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edx + new Register32(0x004916B4/*4789940*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000007C/*124*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			goto loc_42F04B;

			loc_42F00C:
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Esi + emulator.Cpu.Edi * new Register32(1));
			emulator.Cpu.Eax = emulator.Cpu.Shl(emulator.Cpu.Eax, new Register8(0x03/*3*/));
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Eax + new Register32(0x0049175C/*4790108*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Eax + new Register32(0x00491758/*4790104*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000009C/*156*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Eax + new Register32(0x0049195C/*4790620*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Eax + new Register32(0x00491958/*4790616*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000007C/*124*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000084/*132*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);

			loc_42F04B:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Jne) goto loc_42F12C;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000058/*88*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000005C/*92*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Esi + emulator.Cpu.Edi * new Register32(1));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491764/*4790116*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000006C/*108*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491964/*4790628*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(new Register32(0x40C2C080/*1086505088*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Edx + new Register32(0x004916A8/*4789928*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Edx + new Register32(0x004916B0/*4789936*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42F0DF;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42F0DF:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42F0F4;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42F0F4:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491760/*4790112*/)]);
			emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491960/*4790624*/)]);
			emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42F12C:
			emulator.Cpu.Esi = emulator.Cpu.Add(emulator.Cpu.Esi, emulator.Cpu.Edi);
			emulator.Cpu.Esi = emulator.Cpu.Shl(emulator.Cpu.Esi, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000064/*100*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42F165;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42F165:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42F186;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000024/*36*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42F186:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[1]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42F1B3;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42F1B3:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F1D2;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42F1D2:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42F1E1;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fchs(emulator.Cpu.Fpu.Stack[0]);

			loc_42F1E1:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fcom(new Register64(0x4066800000000000)/*180*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F202;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4066800000000000)/*180*/);

			loc_42F202:
			emulator.Cpu.Fcom(new Register64(0x4056800000000000)/*90*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F21B;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4056800000000000)/*90*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsubr(emulator.Cpu.Fpu.Stack[0], new Register64(0x4056800000000000)/*90*/);

			loc_42F21B:
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Edx + new Register32(0x004916B8/*4789944*/)], new Register8(0x01/*1*/));
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fdivr(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			if (emulator.Cpu.Jne) goto loc_42FEF8;
			emulator.Cpu.Edi = emulator.Cpu.Xor(emulator.Cpu.Edi, emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000034/*52*/)] = emulator.Cpu.Mov(new Register32(0x40440000/*1078198272*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42F24D:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F48C;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42F284;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(new Register64(0x4054000000000000)/*80*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F284;
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);
			goto loc_42F28A;

			loc_42F284:
			emulator.Cpu.Fld(new Register64(0x4044000000000000)/*40*/);

			loc_42F28A:
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F373;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0BC200000000000)/*-7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F373;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F373;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x40C2C00000000000)/*9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F373;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)]);
			emulator.Cpu.Fld(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2E0/*4760288*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Shl(emulator.Cpu.Ebx, new Register8(0x08/*8*/));
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2DC/*4760284*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Ebx * new Register32(2) + new Register32(0x00443AA0/*4471456*/)], emulator.Cpu.Ax);
			if (emulator.Cpu.Jb) goto loc_42F378;
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			goto loc_42F378;

			loc_42F373:
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F378:
			emulator.Cpu.Cmp(emulator.Memory16[new Register32(0x00443A90/*4471440*/)], emulator.Cpu.Ax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jl) goto loc_42F484;
			emulator.Cpu.Ebx = emulator.Cpu.Mov(new Register32(0x00491C54/*4791380*/));

			loc_42F38E:
			emulator.Cpu.Test(emulator.Cpu.Edi, emulator.Cpu.Edi);
			if (emulator.Cpu.Jne) goto loc_42F48C;
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Ebx + new Register32(0x000000E4/*228*/)], emulator.Cpu.Di);
			if (emulator.Cpu.Je) goto loc_42F45E;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			if (emulator.Cpu.Je) goto loc_42F45E;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Ebx + new Register32(0x000000FC/*252*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F45E;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebx]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			if (emulator.Cpu.Jne) goto loc_42F3CB;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebx + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Test(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_42F45E;

			loc_42F3CB:
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0C/*12*/));
			if (emulator.Cpu.Je) goto loc_42F45E;
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0B/*11*/));
			if (emulator.Cpu.Je) goto loc_42F45E;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ebx + new Register32(0x000000F4/*244*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Ebx + new Register32(0x000000EC/*236*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Cpu.Edi);
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Esi = emulator.Cpu.Sar(emulator.Cpu.Esi, new Register8(1));
			emulator.Cpu.Edx = emulator.Cpu.Sub(emulator.Cpu.Edx, emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000008C/*140*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Esi = emulator.Cpu.Add(emulator.Cpu.Esi, emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000094/*148*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Ecx * new Register32(1));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000090/*144*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000088/*136*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Esp + new Register32(0x00000090/*144*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x00417BE0/*4291552*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x0C/*12*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42F45E;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F45E:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000064/*100*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, new Register32(0x00000598/*1432*/));
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_42F38E;

			loc_42F484:
			emulator.Cpu.Test(emulator.Cpu.Edi, emulator.Cpu.Edi);
			if (emulator.Cpu.Je) goto loc_42F24D;

			loc_42F48C:
			emulator.Cpu.Cmp(emulator.Cpu.Edi, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FE90;
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000003C/*60*/)]);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Ebx = emulator.Cpu.Xor(emulator.Cpu.Ebx, emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x000000A4/*164*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x000000AC/*172*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);

			loc_42F4C3:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4036800000000000)/*22.5*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F4F8;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42F4F8:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4036800000000000)/*22.5*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42F52D;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42F52D:
			emulator.Cpu.Fld(new Register64(0x4044000000000000)/*40*/);
			emulator.Cpu.Fcom(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ecx = emulator.Cpu.Xor(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000034/*52*/)] = emulator.Cpu.Mov(new Register32(0x40440000/*1078198272*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F99A;
			goto loc_42F567;

			loc_42F561:
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Xor(emulator.Cpu.Ebx, emulator.Cpu.Ebx);

			loc_42F567:
			emulator.Cpu.Cmp(emulator.Cpu.Ecx, emulator.Cpu.Ebx);
			if (emulator.Cpu.Je) goto loc_42F575;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)], emulator.Cpu.Ebx);
			if (emulator.Cpu.Jne) goto loc_42F9AC;

			loc_42F575:
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)], emulator.Cpu.Ebx);
			if (emulator.Cpu.Jne) goto loc_42F594;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(new Register64(0x4054000000000000)/*80*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F594;
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);
			goto loc_42F59A;

			loc_42F594:
			emulator.Cpu.Fld(new Register64(0x4044000000000000)/*40*/);

			loc_42F59A:
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Ecx, emulator.Cpu.Ebx);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			if (emulator.Cpu.Jne) goto loc_42F78A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F68A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0BC200000000000)/*-7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F68A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F68A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x40C2C00000000000)/*9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F68A;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Fld(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2E0/*4760288*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Shl(emulator.Cpu.Edi, new Register8(0x08/*8*/));
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2DC/*4760284*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edi = emulator.Cpu.Add(emulator.Cpu.Edi, emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Edi * new Register32(2) + new Register32(0x00443AA0/*4471456*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jb) goto loc_42F68A;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F68A:
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Cmp(emulator.Memory16[new Register32(0x00443A90/*4471440*/)], emulator.Cpu.Ax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jl) goto loc_42F78A;
			emulator.Cpu.Edi = emulator.Cpu.Mov(new Register32(0x00491C54/*4791380*/));

			loc_42F6A5:
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Edi + new Register32(0x000000E4/*228*/)], new Register8(0x00/*0*/));
			if (emulator.Cpu.Je) goto loc_42F75E;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42F75E;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Edi + new Register32(0x000000FC/*252*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F75E;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edi]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			if (emulator.Cpu.Jne) goto loc_42F6DB;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edi + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Test(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_42F75E;

			loc_42F6DB:
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0C/*12*/));
			if (emulator.Cpu.Je) goto loc_42F75E;
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0B/*11*/));
			if (emulator.Cpu.Je) goto loc_42F75E;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Edi + new Register32(0x000000F4/*244*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Edi + new Register32(0x000000EC/*236*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Esi = emulator.Cpu.Sar(emulator.Cpu.Esi, new Register8(1));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000008C/*140*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Esi = emulator.Cpu.Add(emulator.Cpu.Esi, emulator.Cpu.Ebx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000094/*148*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Ecx * new Register32(1));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000090/*144*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000088/*136*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Esp + new Register32(0x00000090/*144*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x00417BE0/*4291552*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x0C/*12*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42F77E;

			loc_42F75E:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Add(emulator.Cpu.Edi, new Register32(0x00000598/*1432*/));
			emulator.Cpu.Ecx = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_42F6A5;
			goto loc_42F786;

			loc_42F77E:
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)] = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F786:
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000064/*100*/)]);

			loc_42F78A:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)]);
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42F976;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fcom(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F876;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0BC200000000000)/*-7200*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F876;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F876;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x40C2C00000000000)/*9600*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42F876;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Fld(new Register64(0x40BC200000000000)/*7200*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2E0/*4760288*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Fild(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Shl(emulator.Cpu.Edi, new Register8(0x08/*8*/));
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0xC0C2C00000000000)/*-9600*/);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fidiv(emulator.Cpu.Fpu.Stack[0], emulator.Memory32[new Register32(0x0048A2DC/*4760284*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Edi = emulator.Cpu.Add(emulator.Cpu.Edi, emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Edi * new Register32(2) + new Register32(0x00443AA0/*4471456*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jb) goto loc_42F876;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)] = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F876:
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Cmp(emulator.Memory16[new Register32(0x00443A90/*4471440*/)], emulator.Cpu.Ax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jl) goto loc_42F976;
			emulator.Cpu.Edi = emulator.Cpu.Mov(new Register32(0x00491C54/*4791380*/));

			loc_42F891:
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Edi + new Register32(0x000000E4/*228*/)], new Register8(0x00/*0*/));
			if (emulator.Cpu.Je) goto loc_42F94A;
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ebp + new Register32(0x00000008/*8*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Edx);
			if (emulator.Cpu.Je) goto loc_42F94A;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Edi + new Register32(0x000000FC/*252*/)], new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42F94A;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edi]);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			if (emulator.Cpu.Jne) goto loc_42F8C7;
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Edi + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Test(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_42F94A;

			loc_42F8C7:
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0C/*12*/));
			if (emulator.Cpu.Je) goto loc_42F94A;
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x0B/*11*/));
			if (emulator.Cpu.Je) goto loc_42F94A;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Edi + new Register32(0x000000F4/*244*/)]);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ebx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A240/*4760128*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Edi + new Register32(0x000000EC/*236*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Cpu.Esi = emulator.Cpu.Sar(emulator.Cpu.Esi, new Register8(1));
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000008C/*140*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x0048A23C/*4760124*/)]);
			emulator.Cpu.Cdq();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000020/*32*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Sub(emulator.Cpu.Eax, emulator.Cpu.Edx);
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, emulator.Cpu.Esi);
			emulator.Cpu.Eax = emulator.Cpu.Sar(emulator.Cpu.Eax, new Register8(1));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000094/*148*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Eax * new Register32(1));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000090/*144*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000088/*136*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x004360C4/*4415684*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Esp + new Register32(0x00000090/*144*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(new Register32(0x00417BE0/*4291552*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x0C/*12*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42F96A;

			loc_42F94A:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Add(emulator.Cpu.Edi, new Register32(0x00000598/*1432*/));
			emulator.Cpu.Ecx = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000001C/*28*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_42F891;
			goto loc_42F972;

			loc_42F96A:
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)] = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42F972:
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000064/*100*/)]);

			loc_42F976:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Jne) goto loc_42F561;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000004C/*76*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000044/*68*/)]);
			emulator.Cpu.Ebx = emulator.Cpu.Xor(emulator.Cpu.Ebx, emulator.Cpu.Ebx);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Ebx);
			if (emulator.Cpu.Jne) goto loc_42F9AC;

			loc_42F99A:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42F9E6;

			loc_42F9AC:
			emulator.Cpu.Cmp(emulator.Cpu.Ecx, emulator.Cpu.Ebx);
			if (emulator.Cpu.Jne) goto loc_42F9C6;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Fcom(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000B0/*176*/)]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FBD1;

			loc_42F9C6:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Cpu.Cmp(emulator.Cpu.Eax, new Register8(0x07/*7*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000038/*56*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_42F4C3;
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Inc(emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			goto loc_42FF00;

			loc_42F9E6:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3FE0000000000000)/*0.5*/);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fcom(new Register64(0x4044000000000000)/*40*/);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491968/*4790632*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049196C/*4790636*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(new Register32(0x40C2C080/*1086505088*/));
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491770/*4790128*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491774/*4790132*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FA46;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x4044000000000000)/*40*/);

			loc_42FA46:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A8/*168*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Edi, new Register8(0x01/*1*/));
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[2]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			if (emulator.Cpu.Jl) goto loc_42FE87;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491758/*4790104*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491958/*4790616*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FAB8;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42FAB8:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FACD;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42FACD:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FAEC;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FAEC:
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FAFF;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FAFF:
			emulator.Cpu.Cmp(emulator.Cpu.Edi, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FB2F;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000084/*132*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Eax * new Register32(8) + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x004916A8/*4789928*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Eax * new Register32(8) + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x004916B0/*4789936*/)]);
			goto loc_42FB4B;

			loc_42FB2F:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491758/*4790104*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491750/*4790096*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491958/*4790616*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491950/*4790608*/)]);

			loc_42FB4B:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FB6C;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42FB6C:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FB81;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42FB81:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FBA0;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FBA0:
			(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]) = emulator.Cpu.Fxch(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]) = emulator.Cpu.Fxch(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FBBB;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FBBB:
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FDB9;
			goto loc_42FDB3;

			loc_42FBD1:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000030/*48*/)]);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3FE0000000000000)/*0.5*/);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fcom(new Register64(0x4044000000000000)/*40*/);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491968/*4790632*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049196C/*4790636*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(new Register32(0x40C2C080/*1086505088*/));
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491770/*4790128*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491774/*4790132*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FC31;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x4044000000000000)/*40*/);

			loc_42FC31:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x000000A0/*160*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x3F91DF46A2529983)/*0.01745329251994*/);
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Cmp(emulator.Cpu.Edi, new Register8(0x01/*1*/));
			emulator.Cpu.Fld(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fcos(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[2]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000098/*152*/)]);
			emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsin(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000078/*120*/)]);
			emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			if (emulator.Cpu.Jl) goto loc_42FE87;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491758/*4790104*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491958/*4790616*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FCA3;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42FCA3:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FCB8;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42FCB8:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FCD7;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FCD7:
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FCEA;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FCEA:
			emulator.Cpu.Cmp(emulator.Cpu.Edi, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FD1A;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000048/*72*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000084/*132*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Eax * new Register32(8) + new Register32(0x00491760/*4790112*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x004916A8/*4789928*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Eax * new Register32(8) + new Register32(0x00491960/*4790624*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Ecx + new Register32(0x004916B0/*4789936*/)]);
			goto loc_42FD36;

			loc_42FD1A:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491758/*4790104*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491750/*4790096*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491958/*4790616*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Memory64[emulator.Cpu.Esi + new Register32(0x00491950/*4790608*/)]);

			loc_42FD36:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FD57;
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(new Register32(0x3FF00000/*1072693248*/));

			loc_42FD57:
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Je) goto loc_42FD6C;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fld(new Register64(0x3FF0000000000000)/*1*/);

			loc_42FD6C:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000010/*16*/)]);
			emulator.Cpu.Fpu.Stack[1] = emulator.Cpu.Fpatan(emulator.Cpu.Fpu.Stack[1], emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fmul(emulator.Cpu.Fpu.Stack[0], new Register64(0x404CA5DC1A63CBB0)/*57.2957795131*/);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FD8B;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FD8B:
			(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]) = emulator.Cpu.Fxch(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]) = emulator.Cpu.Fxch(emulator.Cpu.Fpu.Stack[0], emulator.Cpu.Fpu.Stack[1]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Je) goto loc_42FDA6;
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FDA6:
			emulator.Cpu.Fcom(new Register64(0x4076800000000000)/*360*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FDB9;

			loc_42FDB3:
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fsub(emulator.Cpu.Fpu.Stack[0], new Register64(0x4076800000000000)/*360*/);

			loc_42FDB9:
			emulator.Cpu.Fcom(new Register64(0x4056800000000000)/*90*/);
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x01/*1*/));
			if (emulator.Cpu.Jne) goto loc_42FE3A;
			emulator.Cpu.Fcom(new Register64(0x4070E00000000000)/*270*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42FE3C;
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fcom(new Register64(0x409F400000000000)/*2000*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x41/*65*/));
			if (emulator.Cpu.Je) goto loc_42FE3C;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000058/*88*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000005C/*92*/)]);
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fadd(emulator.Cpu.Fpu.Stack[0], new Register64(0x4064000000000000)/*160*/);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491764/*4790116*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000006C/*108*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000074/*116*/)]);
			emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Edi = emulator.Cpu.Dec(emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491964/*4790628*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Edi = emulator.Cpu.Inc(emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000074/*116*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			goto loc_42FF00;

			loc_42FE3A:
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();

			loc_42FE3C:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000058/*88*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000005C/*92*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000006C/*108*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491968/*4790632*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049196C/*4790636*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Cpu.Edi = emulator.Cpu.Inc(emulator.Cpu.Edi);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491770/*4790128*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000054/*84*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491774/*4790132*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			goto loc_42FF00;

			loc_42FE87:
			emulator.Cpu.Edi = emulator.Cpu.Inc(emulator.Cpu.Edi);
			emulator.Cpu.Fpu.Stack[0] = emulator.Cpu.Fst(emulator.Cpu.Fpu.Stack[0]);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			goto loc_42FF00;

			loc_42FE90:
			emulator.Cpu.Fld(emulator.Memory64[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)]);
			emulator.Cpu.Fcom(new Register64(0x0000000000000000)/*0*/);
			emulator.Cpu.Fpu.Stack.Pop();
			emulator.Cpu.Ax = emulator.Cpu.Fnstsw();
			emulator.Cpu.Test(emulator.Cpu.Ah, new Register8(0x40/*64*/));
			if (emulator.Cpu.Jne) goto loc_42FEF8;
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000058/*88*/)]);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000005C/*92*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000068/*104*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000006C/*108*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491968/*4790632*/)] = emulator.Cpu.Mov(emulator.Cpu.Ecx);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x0049196C/*4790636*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Inc(emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491770/*4790128*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000050/*80*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000054/*84*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Esi + new Register32(0x00491774/*4790132*/)] = emulator.Cpu.Mov(new Register32(0x40C2C080/*1086505088*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			goto loc_42FF00;

			loc_42FEF8:
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)] = emulator.Cpu.Mov(new Register32(0xFFFFFFFF/*4294967295*/));

			loc_42FF00:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000074/*116*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Esp + new Register32(0x000000B8/*184*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register32(0x00441650/*4462160*/));
			emulator.Cpu.Push(emulator.Cpu.Ecx);
			emulator.Cpu.Call(emulator.Memory32[new Register32(0x0043C164/*4440420*/)]);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463B20/*4602656*/)]);
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x0C/*12*/));
			emulator.Cpu.Test(emulator.Cpu.Ecx, emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_42FF33;
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463AA4/*4602532*/)]);
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(emulator.Cpu.Edx);
			emulator.Cpu.Call(emulator.Memory32[new Register32(0x0043C154/*4440404*/)]);

			loc_42FF33:
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000002C/*44*/)]);
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42EFC9;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463B20/*4602656*/)]);
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Jne) goto loc_42FF59;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[new Register32(0x00463AA4/*4602532*/)]);
			emulator.Cpu.Push(new Register32(0x0044163C/*4462140*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Call(emulator.Memory32[new Register32(0x0043C154/*4440404*/)]);

			loc_42FF59:
			emulator.Cpu.Eax = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));

			loc_42FF5E:
			emulator.Cpu.Edi = emulator.Cpu.Pop32();
			emulator.Cpu.Esi = emulator.Cpu.Pop32();
			emulator.Cpu.Ebx = emulator.Cpu.Pop32();
			emulator.Cpu.Esp = emulator.Cpu.Mov(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Pop32();
			return;

		}
	}
}