// Code generated by: https://github.com/OpenNSPW/Disassembler

using Aigamo.Enzan;

namespace OpenNspw.Interop.Subroutines
{
	// sub_41F300
	internal static class Sub41F300
	{
		public static void Call(Emulator emulator)
		{
			emulator.Cpu.Ecx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000004/*4*/)]);
			emulator.Cpu.Push(emulator.Cpu.Ebp);
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Esi = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(2));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Shl(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			emulator.Cpu.Eax = emulator.Cpu.Add(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(2));
			emulator.Cpu.Ebp = emulator.Cpu.Lea(emulator.Cpu.Eax * new Register32(8) + new Register32(0x00486BCE/*4746190*/));
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Cpu.Ebp);

			loc_41F322:
			emulator.Cpu.Cmp(emulator.Memory16[emulator.Cpu.Eax], new Register8(0x00/*0*/));
			if (emulator.Cpu.Je) goto loc_41F332;
			emulator.Cpu.Esi = emulator.Cpu.Inc(emulator.Cpu.Esi);
			emulator.Cpu.Edx = emulator.Cpu.Inc(emulator.Cpu.Edx);
			emulator.Cpu.Eax = emulator.Cpu.Add(emulator.Cpu.Eax, new Register8(0x02/*2*/));
			emulator.Cpu.Cmp(emulator.Cpu.Edx, new Register8(0x11/*17*/));
			if (emulator.Cpu.Jle) goto loc_41F322;

			loc_41F332:
			emulator.Cpu.Eax = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Cmp(emulator.Cpu.Eax, emulator.Cpu.Edi);
			if (emulator.Cpu.Jl) goto loc_41F3B8;
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(2));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Eax = emulator.Cpu.Shl(emulator.Cpu.Eax, new Register8(0x04/*4*/));
			emulator.Cpu.Eax = emulator.Cpu.Add(emulator.Cpu.Eax, emulator.Cpu.Ecx);
			emulator.Cpu.Ebx = emulator.Cpu.Mov(new Register32(0x00491C38/*4791352*/));
			emulator.Cpu.Eax = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(2));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Esi + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Ecx * new Register32(2) + new Register32(0x00486BCC/*4746188*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);

			loc_41F361:
			emulator.Cpu.Ax = emulator.Cpu.Mov(emulator.Memory16[emulator.Cpu.Ebx]);
			emulator.Cpu.Test(emulator.Cpu.Ax, emulator.Cpu.Ax);
			if (emulator.Cpu.Je) goto loc_41F3A5;
			emulator.Cpu.Cmp(emulator.Cpu.Ax, emulator.Memory16[new Register32(0x00483B4C/*4733772*/)]);
			if (emulator.Cpu.Je) goto loc_41F3A5;
			emulator.Cpu.Cmp(emulator.Memory32[emulator.Cpu.Ebx + new Register32(0x0000001C/*28*/)], new Register8(0x0C/*12*/));
			if (emulator.Cpu.Jne) goto loc_41F3A5;
			emulator.Cpu.Edx = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Cpu.Ebp);
			emulator.Cpu.Ecx = emulator.Cpu.Mov(new Register32(0x00000011/*17*/));

			loc_41F384:
			emulator.Cpu.Esi = emulator.Cpu.Movsx(emulator.Memory16[emulator.Cpu.Eax]);
			emulator.Cpu.Cmp(emulator.Cpu.Esi, emulator.Cpu.Edi);
			if (emulator.Cpu.Jne) goto loc_41F38D;
			emulator.Cpu.Edx = emulator.Cpu.Xor(emulator.Cpu.Edx, emulator.Cpu.Edx);

			loc_41F38D:
			emulator.Cpu.Eax = emulator.Cpu.Add(emulator.Cpu.Eax, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Dec(emulator.Cpu.Ecx);
			if (emulator.Cpu.Jne) goto loc_41F384;
			emulator.Cpu.Test(emulator.Cpu.Edx, emulator.Cpu.Edx);
			if (emulator.Cpu.Je) goto loc_41F3A5;
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)]);
			emulator.Memory16[emulator.Cpu.Eax] = emulator.Cpu.Mov(emulator.Cpu.Di);
			emulator.Cpu.Eax = emulator.Cpu.Add(emulator.Cpu.Eax, new Register8(0x02/*2*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x00000014/*20*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);

			loc_41F3A5:
			emulator.Cpu.Eax = emulator.Cpu.Movsx(emulator.Memory16[new Register32(0x00443A90/*4471440*/)]);
			emulator.Cpu.Edi = emulator.Cpu.Inc(emulator.Cpu.Edi);
			emulator.Cpu.Ebx = emulator.Cpu.Add(emulator.Cpu.Ebx, new Register32(0x00000598/*1432*/));
			emulator.Cpu.Cmp(emulator.Cpu.Edi, emulator.Cpu.Eax);
			if (emulator.Cpu.Jle) goto loc_41F361;
			emulator.Cpu.Ebx = emulator.Cpu.Pop32();

			loc_41F3B8:
			emulator.Cpu.Edi = emulator.Cpu.Pop32();
			emulator.Cpu.Esi = emulator.Cpu.Pop32();
			emulator.Cpu.Ebp = emulator.Cpu.Pop32();
			return;

		}
	}
}