// Code generated by: https://github.com/OpenNSPW/Disassembler

using Aigamo.Enzan;

namespace OpenNspw.Interop.Subroutines
{
	// scenario_107
	internal static class Sub421830
	{
		public static void Call(Emulator emulator)
		{
			emulator.Cpu.Push(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Mov(emulator.Cpu.Esp);
			emulator.Cpu.Esp = emulator.Cpu.And(emulator.Cpu.Esp, new Register8(0xF8/*-8*/));
			emulator.Cpu.Push(emulator.Cpu.Ecx);
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0A77000/*3232198656*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0B19400/*3232863232*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Ebx = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Push(new Register8(0x06/*6*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Memory16[new Register32(0x00489FB0/*4759472*/)] = emulator.Cpu.Mov(new Register16(0x0002/*2*/));
			emulator.Memory16[new Register32(0x00483B4C/*4733772*/)] = emulator.Cpu.Mov(emulator.Cpu.Bx);
			emulator.Memory32[new Register32(0x00489AB0/*4758192*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489AB4/*4758196*/)] = emulator.Cpu.Mov(new Register32(0xC0B20C00/*3232893952*/));
			emulator.Memory32[new Register32(0x00489AB8/*4758200*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489ABC/*4758204*/)] = emulator.Cpu.Mov(new Register32(0xC0A45000/*3231993856*/));
			emulator.Memory32[new Register32(0x00443A48/*4471368*/)] = emulator.Cpu.Mov(new Register32(0x00061A80/*400000*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x04/*4*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0A77000/*3232198656*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0B11C00/*3232832512*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x03/*3*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x58/*88*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0A77000/*3232198656*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0B0A400/*3232801792*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x03/*3*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x409CC000/*1084014592*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0BD6000/*3233636352*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x0B/*11*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x40/*64*/));
			emulator.Cpu.Edi = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x409B8000/*1083932672*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0BD6000/*3233636352*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x10/*16*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0790000/*3229155328*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40890000/*1082720256*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x40/*64*/));
			emulator.Memory32[emulator.Cpu.Esp + new Register32(0x0000000C/*12*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Cpu.Esi = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916C4/*4789956*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916D8/*4789976*/)] = emulator.Cpu.Mov(new Register32(0x00000004/*4*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916C8/*4789960*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491748/*4790088*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491728/*4790056*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049174C/*4790092*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049172C/*4790060*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491760/*4790112*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491764/*4790116*/)] = emulator.Cpu.Mov(new Register32(0xC0C1F800/*3233937408*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491960/*4790624*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491964/*4790628*/)] = emulator.Cpu.Mov(new Register32(0x409CC000/*1084014592*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491768/*4790120*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049176C/*4790124*/)] = emulator.Cpu.Mov(new Register32(0x40C2C080/*1086505088*/));
			emulator.Memory16[emulator.Cpu.Ecx + new Register32(0x00491B88/*4791176*/)] = emulator.Cpu.Mov(new Register16(0x0009/*9*/));

			loc_4219C2:
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0790000/*3229155328*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Cmp(emulator.Cpu.Esi, new Register8(0x07/*7*/));
			emulator.Cpu.Push(new Register32(0x40890000/*1082720256*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			if (emulator.Cpu.Jne) goto loc_421A05;
			emulator.Cpu.Push(new Register8(0x09/*9*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Edx = emulator.Cpu.Mov(new Register32(0x00000032/*50*/));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491B9C/*4791196*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491B98/*4791192*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			goto loc_421A10;

			loc_421A05:
			emulator.Cpu.Push(new Register8(0x07/*7*/));
			emulator.Cpu.Push(emulator.Cpu.Ebx);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));

			loc_421A10:
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916C4/*4789956*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916D8/*4789976*/)] = emulator.Cpu.Mov(emulator.Cpu.Ebx);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x004916C8/*4789960*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);
			emulator.Cpu.Eax = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491748/*4790088*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491728/*4790056*/)] = emulator.Cpu.Mov(emulator.Cpu.Eax);
			emulator.Cpu.Edx = emulator.Cpu.Mov(emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049174C/*4790092*/)]);
			emulator.Cpu.Ax = emulator.Cpu.Mov(emulator.Memory16[emulator.Cpu.Esp + new Register32(0x0000000C/*12*/)]);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x0049172C/*4790060*/)] = emulator.Cpu.Mov(emulator.Cpu.Edx);
			emulator.Memory16[emulator.Cpu.Ecx + new Register32(0x00491B8A/*4791178*/)] = emulator.Cpu.Mov(emulator.Cpu.Ax);
			emulator.Memory16[emulator.Cpu.Ecx + new Register32(0x00491B8C/*4791180*/)] = emulator.Cpu.Mov(emulator.Cpu.Si);
			emulator.Cpu.Esi = emulator.Cpu.Inc(emulator.Cpu.Esi);
			emulator.Cpu.Cmp(emulator.Cpu.Esi, new Register8(0x08/*8*/));
			if (emulator.Cpu.Jle) goto loc_4219C2;
			emulator.Cpu.Push(new Register32(0x004415B0/*4462000*/));
			emulator.Cpu.Call(new Register32(0x00432A30/*4401712*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x04/*4*/));
			emulator.Cpu.Edi = emulator.Cpu.Pop32();
			emulator.Cpu.Esi = emulator.Cpu.Pop32();
			emulator.Cpu.Ebx = emulator.Cpu.Pop32();
			emulator.Cpu.Esp = emulator.Cpu.Mov(emulator.Cpu.Ebp);
			emulator.Cpu.Ebp = emulator.Cpu.Pop32();
			return;

		}
	}
}