// Code generated by: https://github.com/OpenNSPW/Disassembler

using Aigamo.Enzan;

namespace OpenNspw.Interop.Subroutines
{
	// scenario_2
	internal static class Sub42A6C0
	{
		public static void Call(Emulator emulator)
		{
			emulator.Cpu.Push(emulator.Cpu.Esi);
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B77000/*1085763584*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BB5800/*1086019584*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Edi = emulator.Cpu.Mov(new Register32(0x00000001/*1*/));
			emulator.Cpu.Push(new Register8(0x05/*5*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x0A/*10*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x08/*8*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B73E00/*1085750784*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BA5E00/*1085955584*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x05/*5*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x58/*88*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x0A/*10*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x08/*8*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B7D400/*1085789184*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B96400/*1085891584*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x05/*5*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register8(0x11/*17*/));
			emulator.Cpu.Push(new Register8(0x09/*9*/));
			emulator.Cpu.Push(emulator.Cpu.Eax);
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x08/*8*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041F060/*4321376*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x50/*80*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B86A00/*1085827584*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BAF400/*1085993984*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A77F;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Ecx * new Register32(8) + new Register32(0x00491BBC/*4791228*/)] = emulator.Cpu.Mov(new Register32(0x0000001E/*30*/));

			loc_42A77F:
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B87E00/*1085832704*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B9C800/*1085917184*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Esi = emulator.Cpu.Mov(new Register32(0x00000014/*20*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A7B7;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Edx = emulator.Cpu.Shl(emulator.Cpu.Edx, new Register8(0x02/*2*/));
			emulator.Cpu.Edx = emulator.Cpu.Sub(emulator.Cpu.Edx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Edx * new Register32(8) + new Register32(0x00491BBC/*4791228*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);

			loc_42A7B7:
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B68000/*1085702144*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BB3A00/*1086011904*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A7EE;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Ecx * new Register32(8) + new Register32(0x00491BBC/*4791228*/)] = emulator.Cpu.Mov(new Register32(0x0000001E/*30*/));

			loc_42A7EE:
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B6B200/*1085714944*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BA4000/*1085947904*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A821;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Edx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Edx = emulator.Cpu.Shl(emulator.Cpu.Edx, new Register8(0x02/*2*/));
			emulator.Cpu.Edx = emulator.Cpu.Sub(emulator.Cpu.Edx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Edx * new Register32(8) + new Register32(0x00491BBC/*4791228*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);

			loc_42A821:
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B68000/*1085702144*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40B98C00/*1085901824*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x03/*3*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A854;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Memory32[emulator.Cpu.Ecx * new Register32(8) + new Register32(0x00491BBC/*4791228*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);

			loc_42A854:
			emulator.Cpu.Push(new Register32(0x40468000/*1078362112*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0818000/*3229712384*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BC2000/*1086070784*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x0B/*11*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Push(new Register32(0x40568000/*1079410688*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0868000/*3230040064*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BC2000/*1086070784*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x0C/*12*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x40/*64*/));
			emulator.Cpu.Push(new Register32(0x40568000/*1079410688*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC082C000/*3229794304*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BCD400/*1086116864*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Esi = emulator.Cpu.Or(emulator.Cpu.Esi, new Register8(0xFF/*-1*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A8D5;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42A8D5:
			emulator.Cpu.Push(new Register32(0x40468000/*1078362112*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC0854000/*3229958144*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BCDE00/*1086119424*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A913;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42A913:
			emulator.Cpu.Push(new Register32(0x40468000/*1078362112*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC087C000/*3230121984*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BC8E00/*1086098944*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A951;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42A951:
			emulator.Cpu.Push(new Register32(0x40468000/*1078362112*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC08A4000/*3230285824*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BC3E00/*1086078464*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(emulator.Cpu.Edi);
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A98F;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42A98F:
			emulator.Cpu.Push(new Register32(0x40668000/*1080459264*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC08B8000/*3230367744*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BBBC00/*1086045184*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42A9CE;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42A9CE:
			emulator.Cpu.Push(new Register32(0x40668000/*1080459264*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0xC08C2000/*3230408704*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register32(0x40BC0C00/*1086065664*/));
			emulator.Cpu.Push(new Register8(0x00/*0*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Push(new Register8(0x02/*2*/));
			emulator.Cpu.Call(new Register32(0x0041EE20/*4320800*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x20/*32*/));
			emulator.Cpu.Test(emulator.Cpu.Eax, emulator.Cpu.Eax);
			if (emulator.Cpu.Je) goto loc_42AA0D;
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Eax + emulator.Cpu.Eax * new Register32(4));
			emulator.Cpu.Ecx = emulator.Cpu.Lea(emulator.Cpu.Ecx + emulator.Cpu.Ecx * new Register32(8));
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x02/*2*/));
			emulator.Cpu.Ecx = emulator.Cpu.Sub(emulator.Cpu.Ecx, emulator.Cpu.Eax);
			emulator.Cpu.Ecx = emulator.Cpu.Shl(emulator.Cpu.Ecx, new Register8(0x03/*3*/));
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491BD8/*4791256*/)] = emulator.Cpu.Mov(emulator.Cpu.Esi);
			emulator.Memory32[emulator.Cpu.Ecx + new Register32(0x00491754/*4790100*/)] = emulator.Cpu.Mov(emulator.Cpu.Edi);

			loc_42AA0D:
			emulator.Cpu.Push(new Register32(0x004415C8/*4462024*/));
			emulator.Memory16[new Register32(0x00489FB0/*4759472*/)] = emulator.Cpu.Mov(emulator.Cpu.Di);
			emulator.Memory16[new Register32(0x00483B4C/*4733772*/)] = emulator.Cpu.Mov(new Register16(0x0000/*0*/));
			emulator.Memory32[new Register32(0x00489AB0/*4758192*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489AB4/*4758196*/)] = emulator.Cpu.Mov(new Register32(0x40BA9000/*1085968384*/));
			emulator.Memory32[new Register32(0x00489AB8/*4758200*/)] = emulator.Cpu.Mov(new Register32(0x00000000/*0*/));
			emulator.Memory32[new Register32(0x00489ABC/*4758204*/)] = emulator.Cpu.Mov(new Register32(0x40B4B400/*1085584384*/));
			emulator.Memory32[new Register32(0x00443A48/*4471368*/)] = emulator.Cpu.Mov(new Register32(0x00002710/*10000*/));
			emulator.Cpu.Call(new Register32(0x00432A30/*4401712*/));
			emulator.Cpu.Esp = emulator.Cpu.Add(emulator.Cpu.Esp, new Register8(0x04/*4*/));
			emulator.Cpu.Edi = emulator.Cpu.Pop32();
			emulator.Cpu.Esi = emulator.Cpu.Pop32();
			return;

		}
	}
}